using System;
using System.Collections.Generic;
using System.Text;
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Procore.Api.Core.Commitments;
//
//    var workOrderContractCreate = WorkOrderContractCreate.FromJson(jsonString);

namespace Procore.Api.Core.Commitments
{
    public class WorkOrderContractCreate
    {

        [JsonProperty("project_id")] public long ProjectId { get; set; }

        [JsonProperty("work_order_contract")] public WorkOrderContractStruct WorkOrderContract { get; set; }

        public struct WorkOrderContractStruct
        {
            [JsonProperty("actual_completion_date")]
            public DateTimeOffset ActualCompletionDate { get; set; }

            [JsonProperty("contract_estimated_completion_date")]
            public DateTimeOffset ContractEstimatedCompletionDate { get; set; }

            [JsonProperty("contract_start_date")] public DateTimeOffset ContractStartDate { get; set; }

            [JsonProperty("description")] public string Description { get; set; }

            [JsonProperty("exclusions")] public string Exclusions { get; set; }

            [JsonProperty("executed")] public bool Executed { get; set; }

            [JsonProperty("inclusions")] public string Inclusions { get; set; }

            [JsonProperty("invoice_contact_user_ids")]
            public List<long> InvoiceContactUserIds { get; set; }

            [JsonProperty("origin_code")] public string OriginCode { get; set; }

            [JsonProperty("origin_data")] public string OriginData { get; set; }

            [JsonProperty("origin_id")] public string OriginId { get; set; }

            [JsonProperty("number")] public string Number { get; set; }

            [JsonProperty("private")] public bool Private { get; set; }

            [JsonProperty("retainage_percent")] public string RetainagePercent { get; set; }

            [JsonProperty("signed_contract_received_date")]
            public DateTimeOffset SignedContractReceivedDate { get; set; }

            [JsonProperty("status")] public string Status { get; set; }

            [JsonProperty("title")] public string Title { get; set; }

            [JsonProperty("vendor_id")] public long VendorId { get; set; }
        }
    }
}

