using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Globalization;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Procore.Api.Core.Commitments;
//
//    var workOrderContractDetail = WorkOrderContractDetail.FromJson(jsonString);

namespace Procore.Api.Core.Commitments
{

    public class WorkOrderContractDetail
    {
        [JsonProperty("accounting_method")] public string AccountingMethod { get; set; }

        [JsonProperty("actual_completion_date")]
        public DateTimeOffset ActualCompletionDate { get; set; }

        [JsonProperty("approved_change_orders")]
        public string ApprovedChangeOrders { get; set; }

        [JsonProperty("attachments")] public List<Attachment> Attachments { get; set; }

        [JsonProperty("change_order_packages")]
        public List<ChangeOrderPackage> ChangeOrderPackages { get; set; }

        [JsonProperty("change_order_requests")]
        public List<List<ChangeOrderRequest>> ChangeOrderRequests { get; set; }

        [JsonProperty("contract_start_date")] public DateTimeOffset ContractStartDate { get; set; }

        [JsonProperty("contract_estimated_completion_date")]
        public DateTimeOffset ContractEstimatedCompletionDate { get; set; }

        [JsonProperty("created_at")] public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("deleted_at")] public DateTimeOffset DeletedAt { get; set; }

        [JsonProperty("description")] public string Description { get; set; }

        [JsonProperty("exclusions")] public string Exclusions { get; set; }

        [JsonProperty("executed")] public bool Executed { get; set; }

        [JsonProperty("grand_total")] public string GrandTotal { get; set; }

        [JsonProperty("id")] public long Id { get; set; }

        [JsonProperty("inclusions")] public string Inclusions { get; set; }

        [JsonProperty("invoice_contacts")] public List<InvoiceContact> InvoiceContacts { get; set; }

        [JsonProperty("line_items")]
        public List<LineItemStruct> LineItems { get; set; }

        [JsonProperty("number")]
        public string Number { get; set; }

        [JsonProperty("origin_data")] public string OriginData { get; set; }

        [JsonProperty("origin_code")]
        public string OriginCode { get; set; }

        [JsonProperty("origin_id")]
        public long OriginId { get; set; }

        [JsonProperty("payments_issued")]
        public List<PaymentsIssuedStruct> PaymentsIssued { get; set; }

        [JsonProperty("pending_change_orders")]
        public string PendingChangeOrders { get; set; }

        [JsonProperty("pending_revised_contract")]
        public string PendingRevisedContract { get; set; }

        [JsonProperty("percentage_paid")]
        public string PercentagePaid { get; set; }

        [JsonProperty("potential_change_orders")]
        public List<ChangeOrderPackage> PotentialChangeOrders { get; set; }

        [JsonProperty("private")]
        public bool Private { get; set; }

        [JsonProperty("project")]
        public ProjectStruct Project { get; set; }

        [JsonProperty("remaining_balance_outstanding")]
        public string RemainingBalanceOutstanding { get; set; }

        [JsonProperty("requisitions_are_enabled")]
        public bool RequisitionsAreEnabled { get; set; }

        [JsonProperty("retainage_percent")]
        public string RetainagePercent { get; set; }

        [JsonProperty("revised_contract")]
        public string RevisedContract { get; set; }

        [JsonProperty("signed_contract_received_date")]
        public DateTimeOffset SignedContractReceivedDate { get; set; }

        [JsonProperty("status")] public string Status { get; set; }

        [JsonProperty("title")] public string Title { get; set; }

        [JsonProperty("total_draw_requests_amount")]
        public string TotalDrawRequestsAmount { get; set; }

        [JsonProperty("total_payments")] public string TotalPayments { get; set; }

        [JsonProperty("total_requisitions_amount")]
        public string TotalRequisitionsAmount { get; set; }

        [JsonProperty("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }

        [JsonProperty("vendor")]
        public VendorStruct Vendor { get; set; }
    

    public partial class Attachment
    {
        [JsonProperty("id")] public long Id { get; set; }

        [JsonProperty("url")] public Uri Url { get; set; }

        [JsonProperty("filename")] public string Filename { get; set; }
    }

    public partial class ChangeOrderPackage
    {
        [JsonProperty("id")] public long Id { get; set; }

        [JsonProperty("contract_id", NullValueHandling = NullValueHandling.Ignore)]
        public long? ContractId { get; set; }

        [JsonProperty("created_at")] public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("deleted_at")] public DateTimeOffset DeletedAt { get; set; }

        [JsonProperty("due_date")] public DateTimeOffset DueDate { get; set; }

        [JsonProperty("invoiced_date")] public DateTimeOffset InvoicedDate { get; set; }

        [JsonProperty("number")] public string Number { get; set; }

        [JsonProperty("origin_data", NullValueHandling = NullValueHandling.Ignore)]
        public string OriginData { get; set; }

        [JsonProperty("origin_id", NullValueHandling = NullValueHandling.Ignore)]
        public string OriginId { get; set; }

        [JsonProperty("paid_date")] public DateTimeOffset PaidDate { get; set; }

        [JsonProperty("reviewed_at")] public DateTimeOffset ReviewedAt { get; set; }

        [JsonProperty("title")] public string Title { get; set; }

        [JsonProperty("status")] public string Status { get; set; }

        [JsonProperty("updated_at")] public DateTimeOffset UpdatedAt { get; set; }
    }

    public partial class ChangeOrderRequest
    {
        [JsonProperty("id")] public long Id { get; set; }

        [JsonProperty("created_at")] public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("deleted_at")] public DateTimeOffset DeletedAt { get; set; }

        [JsonProperty("due_date")] public DateTimeOffset DueDate { get; set; }

        [JsonProperty("invoiced_date")] public DateTimeOffset InvoicedDate { get; set; }

        [JsonProperty("number")] public string Number { get; set; }

        [JsonProperty("paid_date")] public DateTimeOffset PaidDate { get; set; }

        [JsonProperty("status")] public string Status { get; set; }

        [JsonProperty("title")] public string Title { get; set; }

        [JsonProperty("updated_at")] public DateTimeOffset UpdatedAt { get; set; }
    }

    public struct InvoiceContact
    {
        [JsonProperty("id")] public long Id { get; set; }

        [JsonProperty("business_phone")] public string BusinessPhone { get; set; }

        [JsonProperty("business_phone_extension")]
        public long BusinessPhoneExtension { get; set; }

        [JsonProperty("email")] public string Email { get; set; }

        [JsonProperty("fax_number")] public string FaxNumber { get; set; }

        [JsonProperty("job_title")] public string JobTitle { get; set; }

        [JsonProperty("login_information_id")] public string LoginInformationId { get; set; }

        [JsonProperty("mobile_phone")] public string MobilePhone { get; set; }

        [JsonProperty("name")] public string Name { get; set; }

        [JsonProperty("vendor_name")] public string VendorName { get; set; }
    }

    public struct LineItemStruct
    {
        [JsonProperty("id")] public long Id { get; set; }

        [JsonProperty("amount")] public string Amount { get; set; }

        [JsonProperty("company")]
        public ProjectStruct Company { get; set; }

        [JsonProperty("cost_code")]
        public CostCodeStruct CostCode { get; set; }

        [JsonProperty("created_at")] public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("description")] public string Description { get; set; }

        [JsonProperty("extended_type")] public string ExtendedType { get; set; }

        [JsonProperty("holder")] public HolderStruct Holder { get; set; }

        [JsonProperty("line_item_type")]
        public LineItemTypeStruct LineItemType { get; set; }

        [JsonProperty("origin_data")] public string OriginData { get; set; }

        [JsonProperty("origin_id")] public long OriginId { get; set; }

        [JsonProperty("position")] public long Position { get; set; }

        [JsonProperty("project")]
        public ProjectStruct Project { get; set; }

        [JsonProperty("quantity")] public string Quantity { get; set; }

        [JsonProperty("total_amount")] public string TotalAmount { get; set; }

        [JsonProperty("extended_amount")] public string ExtendedAmount { get; set; }

        [JsonProperty("unit_cost")] public string UnitCost { get; set; }

        [JsonProperty("uom")] public string Uom { get; set; }

        [JsonProperty("updated_at")] public DateTimeOffset UpdatedAt { get; set; }
    }

    public struct ProjectStruct
    {
        [JsonProperty("id")] public long Id { get; set; }

        [JsonProperty("name")] public string Name { get; set; }
    }

    public struct CostCodeStruct
    {
        [JsonProperty("id")] public long Id { get; set; }

        [JsonProperty("biller")] public string Biller { get; set; }

        [JsonProperty("biller_id")] public long BillerId { get; set; }

        [JsonProperty("biller_type")] public string BillerType { get; set; }

        [JsonProperty("budgeted")] public bool Budgeted { get; set; }

        [JsonProperty("code")] public string Code { get; set; }

        [JsonProperty("created_at")] public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("deleted_at")] public DateTimeOffset DeletedAt { get; set; }

        [JsonProperty("full_code")] public string FullCode { get; set; }

        [JsonProperty("name")] public string Name { get; set; }

        [JsonProperty("origin_data")] public string OriginData { get; set; }

        [JsonProperty("origin_id")] public string OriginId { get; set; }

        [JsonProperty("parent")] public ParentStruct Parent { get; set; }

        [JsonProperty("position")] public long Position { get; set; }

        [JsonProperty("sortable_code")] public string SortableCode { get; set; }

        [JsonProperty("standard_cost_code_id")]
        public long StandardCostCodeId { get; set; }

        [JsonProperty("updated_at")] public DateTimeOffset UpdatedAt { get; set; }

        [JsonProperty("line_item_types")] public List<LineItemTypeStruct> LineItemTypes { get; set; }
    }

    public struct LineItemTypeStruct
    {
        [JsonProperty("id")] public long Id { get; set; }

        [JsonProperty("name")] public string Name { get; set; }

        [JsonProperty("code")] public string Code { get; set; }

        [JsonProperty("base_type")] public string BaseType { get; set; }

        [JsonProperty("origin_data")] public string OriginData { get; set; }

        [JsonProperty("origin_id")] public string OriginId { get; set; }
    }

    public struct ParentStruct
    {
        [JsonProperty("id")] public long Id { get; set; }
    }

    public struct HolderStruct
    {
        [JsonProperty("id")] public long Id { get; set; }

        [JsonProperty("holder_type")] public string HolderType { get; set; }
    }

    public struct PaymentsIssuedStruct
    {
        [JsonProperty("id")] public long Id { get; set; }

        [JsonProperty("amount")] public string Amount { get; set; }

        [JsonProperty("check_number")] public string CheckNumber { get; set; }

        [JsonProperty("created_at")] public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("date")] public DateTimeOffset Date { get; set; }

        [JsonProperty("draw_request_number")] public long DrawRequestNumber { get; set; }

        [JsonProperty("invoice_number")] public string InvoiceNumber { get; set; }

        [JsonProperty("notes")] public string Notes { get; set; }

        [JsonProperty("payment_number")] public long PaymentNumber { get; set; }

        [JsonProperty("attachments")] public List<Attachment> Attachments { get; set; }

        [JsonProperty("origin_id")] public string OriginId { get; set; }

        [JsonProperty("origin_data")] public string OriginData { get; set; }
    }

    public struct VendorStruct
    {
        [JsonProperty("id")] public long Id { get; set; }

        [JsonProperty("company")] public string Company { get; set; }

        [JsonProperty("origin_data")] public string OriginData { get; set; }

        [JsonProperty("origin_id")] public string OriginId { get; set; }
    }
}

}



